### ISSUE TITLE
treadmill with damaged control panel

### ISSUE THREAD

**Issue by melidron** [gokulnathanperumal/Treadism#1]
I have a treadmill with damaged control panel... How I know if my motor board support I2C comunication so I can connect it with arduino as u suggest in your scheme?
Is thereany otherway toconnect arduino board with the motor board so I can replace the damaged control board woth the arduino board to control the treadmill?
Thanks in advanced

**Comment by gokulnathanperumal** [comment]
You need to study your treadmill's control panel and main board to understand what communication protocol it uses and what data it transfer for each functions and the Arduino should mimic that.

**Comment by melidron** [comment]
> You need to study your treadmill's control panel and main board to understand what communication protocol it uses and what data it transfer for each functions and the Arduino should mimic that.

i have only motor board working control board not work anymore...I have no idea how I understand what protocol it uses...
![12 PINS](https://github.com/user-attachments/assets/a3f2be73-fe04-440b-aeec-1770ebe18659)
I send a draw of the pins the motor board has on it... I hope it helps somehow
